# add_packages.yml
---
- name: yum_install_packages
  ansible.builtin.yum:
    name: "{{ centos_packages_to_add }}"
    state: latest
  when: ansible_pkg_mgr == 'yum'

- name: dnf_install_packages
  ansible.builtin.dnf:
    name: "{{ fedora_packages_to_add + packages_to_add }}"
    state: latest
  when: ansible_pkg_mgr == 'dnf'

- name: xbps_install_packages
  ansible.builtin.xbps:
    name:   "{{ void_packages_to_add }}"
    state:  latest
  when: ansible_pkg_mgr == 'xbps'

- name: apt_install_packages
  ansible.builtin.apt:
    name:   "{{ apt_packages_to_add + packages_to_add }}"
    state:  latest
  when: ansible_pkg_mgr == 'apt'

