# base_server_configs.yml
# Set up the infrastrucutre and 'normal' stuff.

- block:
  - name: service_chrony_on
    service:
      name:     chronyd
      enabled:  yes 

  when: ansible_pkg_mgr == "dnf"

- block:
  - name: sysvinit_chrony_on
    ansible.builtin.sysvinit:
      name:     chrony
      state:    started
      enabled:  yes

  when: ansible_distribution == "Devuan"

- name: copy_in_hosts_file
  copy:
    src:    hosts
    dest:   /etc/hosts
    mode:   0644
    owner:  root
    group:  root

