# roles/compile_python/vars/main.yml
---
src_dir:    "/usr/local/src"
git_dir:    "{{ src_dir }}/cpython"
log_dir:    "/opt/backup/logs"
log_prefix: "{{ log_dir }}/{{ ansible_hostname }}_{{ item }}"
log_suffix: "{{ datetime }}.log"

cpython_repo: 'https://github.com/python/cpython.git'
cpython_branch: "main"

cpython_versions:
  - 'main'
  - '3.13'
  - '3.12'

ulb: "/usr/local/bin"
uli: "/usr/local/include"
ull: "/usr/local/lib"
ullp: "/usr/local/lib/pkgconfig"
ulsmm1: "/usr/local/share/man/man1"

apt_packages_to_add:
  - 'build-essential'
  - 'gdb'
  - 'lcov'
  - 'pkg-config'
  - 'libbz2-dev'
  - 'libffi-dev'
  - 'libgdbm-dev'
  - 'libgdbm-compat-dev'
  - 'liblzma-dev'
  - 'libncurses5-dev'
  - 'libreadline6-dev'
  - 'libsqlite3-dev'
  - 'libssl-dev'
  - 'lzma'
  - 'lzma-dev'
  - 'make'
  - 'tk-dev'
  - 'uuid-dev' 
  - 'zlib1g-dev'


xbps_packages_to_add:
  - 'xz'
  - 'sqlite-devel'
  - 'bzip2-devel'
  - 'gdbm-devel'
  - 'liblzma-devel'
  - 'make'
  - 'tk-devel'
  - 'readline-devel'
  - 'ncurses-devel'
  - 'libuuid-devel'
  - 'zlib-devel'


dnf_packages_to_add:
  - 'bzip2-devel'
  - 'expat'
  - 'expat-devel'
  - 'gcc'
  - 'gcc-c++'
  - 'gdb'
  - 'gdbm-devel'
  - 'gdbm-libs'
  - 'git'
  - 'glibc-devel'
  - 'libffi-devel'
  - 'libstdc++-devel'
  - 'libuuid-devel'
  - 'make'
  - 'mpdecimal'
  - 'openssl-devel'
  - 'perf'
  - 'pkg-config'
  - 'python3-pip'
  - 'readline-devel'
  - 'sqlite'
  - 'sqlite-devel'
  - 'sqlite-libs'
  - 'tk'
  - 'tk-devel'
  - 'xz'
  - 'xz-devel'
  - 'zlib-devel'

ulb_to_remove:
  - '2to3'
  - '2to3-3.12'
  - 'idle3'
  - 'idle3.12'
  - 'idle3.13'
  - 'idle3.14'
  - 'pip3'
  - 'pip3.12'
  - 'pip3.13'
  - 'pip3.14'
  - 'pydoc3'
  - 'pydoc3.12'
  - 'pydoc3.13'
  - 'pydoc3.14'
  - 'python3'
  - 'python3.12'
  - 'python3.12-config'
  - 'python3.12d'
  - 'python3.12d-config'
  - 'python3.13'
  - 'python3.13-config'
  - 'python3.13d'
  - 'python3.13d-config'
  - 'python3.14'
  - 'python3.14-config'
  - 'python3.14d'
  - 'python3.14d-config'
  - 'python3-config'

ull_to_remove:
  - 'libpython3.12d.a'
  - 'libpython3.13d.a'
  - 'libpython3.14d.a'
  - 'python3.12'
  - 'python3.13'
  - 'python3.14'

ullp_to_remove:
  - 'python-3.12d-embed.pc'
  - 'python-3.12d.pc'
  - 'python-3.12-embed.pc'
  - 'python-3.12.pc'
  - 'python-3.13d-embed.pc'
  - 'python-3.13d.pc'
  - 'python-3.13-embed.pc'
  - 'python-3.13.pc'
  - 'python-3.14d-embed.pc'
  - 'python-3.14d.pc'
  - 'python-3.14-embed.pc'
  - 'python-3.14.pc'
  - 'python3-embed.pc'
  - 'python3.pc'

ulsmm1_to_remove:
  - 'python3.1'
  - 'python3.12.1'
  - 'python3.13.1'
  - 'python3.14.1'

uli_to_remove:
  - 'python3.12d'
  - 'python3.13d'
  - 'python3.14d'



