---
log_prefix: "{{ log_dir }}/{{ ansible_hostname }}_{{ item }}"
log_suffix: "{{ datetime }}.log"

cpython_versions:
  - 'main'
  - '3.13'
  - '3.12'

apt_packages_to_add:
  - 'build-essential'
  - 'gdb'
  - 'lcov'
  - 'pkg-config'
  - 'libbz2-dev'
  - 'libffi-dev'
  - 'libgdbm-dev'
  - 'libgdbm-compat-dev'
  - 'liblzma-dev'
  - 'libncurses5-dev'
  - 'libreadline6-dev'
  - 'libsqlite3-dev'
  - 'libssl-dev'
  - 'lzma'
  - 'lzma-dev'
  - 'make'
  - 'tk-dev'
  - 'uuid-dev' 
  - 'zlib1g-dev'


xbps_packages_to_add:
  - 'xz'
  - 'sqlite-devel'
  - 'bzip2-devel'
  - 'gdbm-devel'
  - 'liblzma-devel'
  - 'tk-devel'
  - 'readline-devel'
  - 'ncurses-devel'
  - 'libuuid-devel'
  - 'zlib-devel'

