# roles/compile_python/vars/main.yml
---
src_dir:    "/usr/local/src"
git_dir:    "{{ src_dir }}/cpython"
log_dir:    "/opt/backup/logs"
log_prefix: "{{ log_dir }}/{{ ansible_hostname }}_{{ item }}"
log_suffix: "{{ datetime }}.log"

cpython_repo: 'https://github.com/python/cpython.git'
cpython_branch: "main"

cpython_versions:
  - 'main'
  - '3.13'
  - '3.12'

apt_packages_to_add:
  - 'build-essential'
  - 'gdb'
  - 'lcov'
  - 'pkg-config'
  - 'libbz2-dev'
  - 'libffi-dev'
  - 'libgdbm-dev'
  - 'libgdbm-compat-dev'
  - 'liblzma-dev'
  - 'libncurses5-dev'
  - 'libreadline6-dev'
  - 'libsqlite3-dev'
  - 'libssl-dev'
  - 'lzma'
  - 'lzma-dev'
  - 'make'
  - 'tk-dev'
  - 'uuid-dev' 
  - 'zlib1g-dev'


xbps_packages_to_add:
  - 'xz'
  - 'sqlite-devel'
  - 'bzip2-devel'
  - 'gdbm-devel'
  - 'liblzma-devel'
  - 'tk-devel'
  - 'readline-devel'
  - 'ncurses-devel'
  - 'libuuid-devel'
  - 'zlib-devel'

dnf_packages_to_add:
  - 'gcc'
  - 'gcc-c++'
  - 'gdb'
  - 'xz'
  - 'xz-devel'
  - 'glibc-devel'
  - 'libstdc++-devel'
  - 'openssl-devel'
  - 'readline-devel'
  - 'zlib-devel'
  - 'libffi-devel'
  - 'bzip2-devel'
  - 'xz-devel'
  - 'sqlite'
  - 'sqlite-devel'
  - 'sqlite-libs'
  - 'libuuid-devel'
  - 'gdbm-libs'
  - 'perf'
  - 'expat'
  - 'expat-devel'
  - 'mpdecimal'
  - 'python3-pip'
  - 'git'
  - 'pkg-config'

