---

- name: checkout_version
  ansible.builtin.command:
    argv: 
      - git 
      - checkout
      - "{{ item }}"
  args:
    chdir: "{{ git_dir }}"


- name: configure
  ansible.builtin.command:
    argv:
      - ./configure
      - --with-pydebug
  args:
    chdir:  "{{ git_dir }}"
  register: config_results


- name: log_config_results
  ansible.builtin.copy:
    content:  "{{ config_results }}"
    dest:     "{{ log_prefix }}_configure_{{ log_suffix }}"    
  delegate_to: localhost


- name: make
  community.general.make:
    chdir:    "{{ git_dir }}"
  register:   make_results


- name: log_make_results
  ansible.builtin.copy:
    content:  "{{ make_results }}"
    dest:     "{{ log_prefix }}_make_{{ log_suffix }}"    
  delegate_to: localhost


- name: make_regen_global_objects
  community.general.make:
    target:   regen-global-objects
    chdir:    "{{ git_dir }}"
  register:   make_regen_global_objects_results
  # this target does not exist before 3.11
  ignore_errors:  true

- name: log_make_regen_global_objects_results
  ansible.builtin.copy:
    content:  "{{ make_regen_global_objects_results }}"
    dest:     "{{ log_prefix }}_make_regen_global_objects_{{ log_suffix }}"    
  delegate_to: localhost
  

- name: run_tests
  ansible.builtin.command:
    argv:
      - ./python
      - -m
      - test
      - -uall 
      - -j0
  args:
    chdir:  "{{ git_dir }}"
  register:       test_results
  ignore_errors:  true

- name: log_test_results
  ansible.builtin.copy:
    content:  "{{ test_results }}"
    dest:     "{{ log_prefix }}_test_{{ log_suffix }}"    
  delegate_to: localhost


- name: make_distclean
  community.general.make:
    target: distclean
    chdir:  "{{ git_dir }}"




