# roles/compile_python/tasks/main/yml
---

- name: set_up_packages_and_directories
  block:
    - name: install_xbps_packages
      ansible.builtin.xbps:
        name:   "{{ item }}"
        state:  latest
      with_items:
        - "{{ xbps_packages_to_add }}"
      when: ansible_pkg_mgr == "xbps"

    - name: install_apt_packages
      ansible.builtin.apt:
        name:         "{{ item }}"
        state:        latest
        update_cache: true
        autoclean:    true
        autoremove:   true
        clean:        true
      with_items:
        - "{{ apt_packages_to_add }}"
      when: ansible_pkg_mgr == "apt"

    - name: make_control_node_log_dir
      ansible.builtin.file:
        path:   "{{ log_dir }}"
        state:  directory
        group:  syseng
        mode:   g=rwx
        owner:  root
      delegate_to: localhost

    - name: make_target_node_src_dir
      ansible.builtin.file:
        path:   "{{ src_dir }}"
        state:  directory
        group:  syseng
        mode:   g=rwx
        owner:  root

  become: true
  become_user: root


- name: git_get
  ansible.builtin.git:
    repo:     "{{ cpython_repo }}"
    dest:     "{{ git_dir }}"
    version:  "{{ cpython_branch }}"
    clone:    true


- name: do_selected_branches
  include_tasks: compile.yml
  vars:
    version:  "{{ item }}"
  with_items: "{{ cpython_versions }}"

