# new_server.yml
# All the basic configs.
---
- hosts:  all
  become: true

  tasks:
    - include: tasks/remove_resolver_symlink.yml

    - include: tasks/base_server_configs.yml

    - include: tasks/patch.yml

    - include: tasks/add_packages.yml

    - include: tasks/remove_packages.yml

    #- include: tasks/reboot_node_tasks.yml


