---
# Patch servers
- hosts:  all
  become: true


  tasks:
    - name: patch_yum_based_hosts
      yum:
        name: "*"
        state: latest
      when: ansible_pkg_mgr == 'yum'

    - name: patch_dnf_based_hosts
      dnf:
        name: "*"
        state: latest
      when: ansible_pkg_mgr == 'dnf'

    - name: patch_void_linux
      #command: /usr/bin/xbps-install -Suvy
      xbps: upgrade=yes
      when: ansible_pkg_mgr == 'xbps'

    - name: patch_devuan_linux
      ansible.builtin.apt:
        upgrade:      true
        update_cache: true
        autoclean:    true
        autoremove:   true
        clean:        true
        state:        latest
      when: ansible_pkg_mgr == 'apt'

    - name: ensure_forcefsck_present
      file:
        name:   /forcefsck
        state:  touch

