---
# Patch servers
- hosts:  all
  become: true


  tasks:
    - name: patch_yum_based_hosts
      yum:
        name: "*"
        state: latest
      when: ansible_distribution == 'CentOS'

    - name: patch_dnf_based_hosts
      dnf:
        name: "*"
        state: latest
      when: ansible_distribution == 'Fedora'

    - name: ensure_forcefsck_present
      file:
        name:   /forcefsck
        state:  touch
      when: ansible_distribution == 'CentOS'

    - name: patch_void_linux
      #command: /usr/bin/xbps-install -Suvy
      xbps: upgrade=yes
      when: ansible_distribution == 'void'
